name: Code Review
on: 
  push:
      branches: 
        - main
  pull_request:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses : actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage
      - name: Run tests with pytest
        run: coverage run pytest tests/test_code.py
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1 
